language: node_js

node_js:
  - "0.10"

install:
  - npm install

after_success:
  - npm run coveralls

before_deploy:
  - npm run bundle

deploy:
  # deploy to npm
  - provider: npm
    email: "aleksey.dmitrich@gmail.com"
    skip_cleanup: true
    on:
      tags: true
    api_key:
      secure: "ZphlRLtmUL88ooFU5A1vPUNzSU/c+A7inyrQ11SSmRfoukLY09Xxc+I6sGzVl37Az1p7s967Zm7AJyBZnV3QVI1gvBI4CIdIywmPSrHHTIO7T8L5qK8FX5TfgN5ScD7wtyx2/N0KdNT+q5laJ95XuK/8CPYvrmQGxJ8Oh4b/cT6QOaq9Vat0OdoY0rttYoU9UtszKXQMHndqXs46PA0jyqrJ7eEdhUI2AyZkwVZP/b1dnA6SCzrvrIrDEt8tNqIwT09ln/+myv5WgdRm6pDRd4jKzm5Me334nQjQgBiHggmDnw1E9N8/ZcXtDd04YfQFwScVHtBpEJDuhqYhHfVDaMIXflTp/zUnp9z0cmMpDixJfgIMIqFSfURqPqrN5a2RyPkJe1lfvpd0uw9Q8kqVt1EeTgvb7GegvehTv9MKdEgRKlUfuHKjot1vZT2/MXyA15k20Fpv4QgZO3gZGtMWni66IHF6aHlcoUZsI/jEKqS0HlSdfuW266TRmu66t+ayh9WiScZyS28tEdAuK8/YXn8hdAD3qery78KqWecEvWG/ba4Gm7jIR59KW83XlLUXnXw7qmgY6yX7abui0hoai6PqRzd5vKH290b0QS72ryTdHZpg1+50oMmzkdOX/EpJAjqKm2cHCcGu8iHs+dAbc6xUoBstVgT/3BJ05c43o88="

  # deploy to github release
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
    api_key:
      secure: "Es/wJFl/HMEQaaPVhPn/N9VqMIi6QkLBT7zJkOZX+H8lJvgbqegl7T9kyvaxCyLT420pI5asv1EkHEWTKChF+Wn9uU9Da//P8ToJ4WdR3yoSorAdS55k0+QXrOR8esvZ06OCsw4Qz3S//3nTcfX5p7ueO+StDiUQfPNnKQYZQdg3s2Vcvrxaya97auE2AJyDLPJMUNNwhzma3qdsX98wgjfRj81uH1Sob+U5AmlA+zOHklpWskzgdcheW/TdrbV/JjkPVqvdQmWOwYEJOJun+QSbXDAO5YATTcWE2kYguKcXTUJKuDJ+G+PtoypjcARG/sQTNpgADuuT/2O2nJDlNKctUMlTPtO3aegsaKG0PtAkPHh5Be+kA+pjCXPuEwyLdx0KzNWzTzLvg9P+wOtHYvo+XiHXVXM1F4MTrkTmoiiebWU7fVgfUqHZGDpNCEKqNI3HCDVZquN9Dvb/pu4NPjH3Z/C+RVoDVUad0Fn2hqqT8R2sAZpGl++cDPhah5XCYnpVpz3SG2z309QjJQmMK/zrL5OC63YSPjyn91bjnFk+w+2bs80sq+Xzxzx/akMuG6oPZCOKytC++Kw4xHX6pSqNt8pfoyEbHmISqpBSO2cHWCN5DmauN8GF8jzKeGZuVABJOypYaGA9BVPTT+PCIWsxQYw4cM6VVEuypA6/vSw="
    file: "./dist/sinon-chrome.latest.js"

